'use client'

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { TreatmentPlan } from '@/lib/schemas/plan';
import { TherapistView } from './TherapistView';
import { ClientView } from './ClientView';
import { PlanEditor } from './PlanEditor';
import { PlanHistory } from './PlanHistory';
import { GoalTimeline } from './GoalTimeline';
import { SuggestionReviewPanel } from '@/components/suggestion/SuggestionReviewPanel';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertCircle, Eye, EyeOff, Edit, Clock, FileText, TrendingUp, Sparkles, Loader2, ArrowLeft, History } from 'lucide-react';
import { SafetyCheckResult, RiskLevel } from '@/lib/types/safety';
import { cn } from '@/lib/utils';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from '@/components/ui/scroll-area';
import type { SuggestedChanges } from '@/lib/schemas/suggestion';

interface DualViewPlanProps {
  plan: TreatmentPlan;
  planId?: string; // Needed for API updates
  sessionId?: string; // Needed for Update Plan feature
  safetyResult?: SafetyCheckResult;
  transcript?: string;
  onPlanUpdated?: (newPlan: TreatmentPlan) => void; // Callback to parent to refresh
}

/**
 * Suggestion data for the review panel
 */
interface SuggestionData {
  id: string;
  sessionSummary: string;
  progressNotes: string | null;
  suggestedChanges: SuggestedChanges;
  createdAt: string;
}

type ViewMode = 'therapist' | 'client';

const AI_DISCLAIMER = "Generated by AI Assistant. This is not a substitute for clinical judgment. Please review carefully.";

/**
 * Historical version data
 */
interface HistoricalVersion {
  id: string;
  version: number;
  content: TreatmentPlan;
  changeType: string;
  changeSummary: string | null;
  createdAt: string;
}

export function DualViewPlan({ plan: initialPlan, planId, sessionId, safetyResult, transcript, onPlanUpdated }: DualViewPlanProps) {
  const [plan, setPlan] = useState<TreatmentPlan>(initialPlan);
  const [viewMode, setViewMode] = useState<ViewMode>('therapist');
  const [isEditing, setIsEditing] = useState(false);
  const [isLoadingSuggestion, setIsLoadingSuggestion] = useState(false);
  const [selectedSuggestion, setSelectedSuggestion] = useState<SuggestionData | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [historicalVersion, setHistoricalVersion] = useState<HistoricalVersion | null>(null);
  const [isLoadingVersion, setIsLoadingVersion] = useState(false);
  const [selectedVersionId, setSelectedVersionId] = useState<string | null>(null);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const router = useRouter();

  const isHighRisk = safetyResult && safetyResult.riskLevel === RiskLevel.HIGH;
  const isViewingHistory = historicalVersion !== null;
  const displayPlan = isViewingHistory ? historicalVersion.content : plan;

  /**
   * Trigger AI analysis and open review dialog with fresh suggestions
   */
  const handleUpdatePlan = async () => {
    if (!sessionId) return;

    setIsLoadingSuggestion(true);
    try {
      const res = await fetch(`/api/sessions/${sessionId}/analyze`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ force: true }),
      });

      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.error || 'Failed to analyze session');
      }

      const data = await res.json();
      if (data.suggestion) {
        setSelectedSuggestion({
          id: data.suggestion.id,
          sessionSummary: data.suggestion.sessionSummary,
          progressNotes: data.suggestion.progressNotes,
          suggestedChanges: data.suggestion.suggestedChanges,
          createdAt: data.suggestion.createdAt,
        });
      }
    } catch (error) {
      console.error('Failed to analyze session:', error);
    } finally {
      setIsLoadingSuggestion(false);
    }
  };

  /**
   * Handle approve action
   */
  const handleApprove = async (modifications?: Partial<SuggestedChanges>, therapistNotes?: string) => {
    if (!selectedSuggestion) return;

    setIsProcessing(true);
    try {
      const res = await fetch(`/api/suggestions/${selectedSuggestion.id}/approve`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ modifications, therapistNotes }),
      });

      if (!res.ok) {
        const error = await res.json();
        throw new Error(error.error || 'Failed to approve');
      }

      const result = await res.json();

      // Update local plan state
      if (result.updatedPlan) {
        setPlan(result.updatedPlan);
        if (onPlanUpdated) onPlanUpdated(result.updatedPlan);
      }

      setSelectedSuggestion(null);
      router.refresh();
    } catch (error) {
      console.error('Failed to approve suggestion:', error);
    } finally {
      setIsProcessing(false);
    }
  };

  /**
   * Handle reject action
   */
  const handleReject = async (reason: string) => {
    if (!selectedSuggestion) return;

    setIsProcessing(true);
    try {
      const res = await fetch(`/api/suggestions/${selectedSuggestion.id}/reject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reason }),
      });

      if (!res.ok) {
        const error = await res.json();
        throw new Error(error.error || 'Failed to reject');
      }

      setSelectedSuggestion(null);
      router.refresh();
    } catch (error) {
      console.error('Failed to reject suggestion:', error);
    } finally {
      setIsProcessing(false);
    }
  };

  /**
   * Handle version selection from history panel
   */
  const handleVersionSelect = async (versionId: string, isCurrentVersion: boolean) => {
    if (isCurrentVersion) {
      // Switching back to current version
      setHistoricalVersion(null);
      setSelectedVersionId(null);
      return;
    }

    if (!planId) return;

    setIsLoadingVersion(true);
    setSelectedVersionId(versionId);
    try {
      const res = await fetch(`/api/plans/${planId}/versions/${versionId}`);
      if (!res.ok) {
        throw new Error('Failed to fetch version');
      }
      const data = await res.json();
      setHistoricalVersion({
        id: data.version.id,
        version: data.version.version,
        content: data.version.content as TreatmentPlan,
        changeType: data.version.changeType,
        changeSummary: data.version.changeSummary,
        createdAt: data.version.createdAt,
      });
    } catch (error) {
      console.error('Failed to load version:', error);
      setSelectedVersionId(null);
    } finally {
      setIsLoadingVersion(false);
    }
  };

  /**
   * Return to current version
   */
  const handleBackToCurrent = () => {
    setHistoricalVersion(null);
    setSelectedVersionId(null);
  };

  const handleSave = async (updatedPlan: TreatmentPlan) => {
    if (!planId) {
        // If no ID (e.g. demo mock mode), just update local state
        setPlan(updatedPlan);
        setIsEditing(false);
        return;
    }

    // Call API
    const res = await fetch(`/api/plans/${planId}/update`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updatedPlan)
    });

    if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || "Failed to update plan");
    }

    // Success
    setPlan(updatedPlan);
    setIsEditing(false);
    if (onPlanUpdated) onPlanUpdated(updatedPlan);
  };

  if (isEditing) {
      return <PlanEditor plan={plan} onSave={handleSave} onCancel={() => setIsEditing(false)} />;
  }

  return (
    <div className="space-y-6">
      {/* Historical Version Banner */}
      {isViewingHistory && (
        <Alert className="bg-amber-50 border-amber-200">
          <History className="h-4 w-4 text-amber-600" />
          <AlertTitle className="text-amber-800">Viewing Historical Version</AlertTitle>
          <AlertDescription className="text-amber-700">
            <div className="flex items-center justify-between">
              <span>
                You are viewing Version {historicalVersion.version} from{' '}
                {new Date(historicalVersion.createdAt).toLocaleDateString()}.
                This is a read-only view.
              </span>
              <Button
                variant="outline"
                size="sm"
                onClick={handleBackToCurrent}
                className="ml-4 border-amber-300 hover:bg-amber-100"
              >
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back to Current
              </Button>
            </div>
          </AlertDescription>
        </Alert>
      )}

      {/* Loading Version Indicator */}
      {isLoadingVersion && (
        <div className="flex items-center justify-center p-4 bg-muted/50 rounded-md">
          <Loader2 className="h-5 w-5 animate-spin mr-2" />
          <span className="text-sm text-muted-foreground">Loading version...</span>
        </div>
      )}

      {/* Safety Alert Banner */}
      {isHighRisk && !isViewingHistory && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Safety Alert Detected</AlertTitle>
          <AlertDescription>
            {safetyResult.reasoning || "High-risk content was identified during analysis. Please review this plan with extreme caution."}
          </AlertDescription>
        </Alert>
      )}

      <Tabs defaultValue="plan" className="w-full">
        <div className="flex flex-wrap gap-3 justify-between items-center mb-4">
            <TabsList className="flex-shrink-0">
                <TabsTrigger value="plan">Treatment Plan</TabsTrigger>
                <TabsTrigger value="goals" disabled={!planId || isViewingHistory}>
                    <TrendingUp className="h-4 w-4 mr-1" />
                    Goal Progress
                </TabsTrigger>
                <TabsTrigger value="transcript" disabled={!transcript || isViewingHistory}>
                    Transcript
                </TabsTrigger>
            </TabsList>

            <div className="flex gap-2 items-center flex-shrink-0">
                {/* Only show Update Plan and Edit Plan when viewing current version */}
                {!isViewingHistory && (
                    <>
                        {sessionId && (
                            <Button
                                variant="default"
                                size="sm"
                                onClick={handleUpdatePlan}
                                disabled={isLoadingSuggestion}
                            >
                                {isLoadingSuggestion ? (
                                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                                ) : (
                                    <Sparkles className="h-4 w-4 mr-2" />
                                )}
                                Update Plan
                            </Button>
                        )}
                        <Button variant="outline" size="sm" onClick={() => setIsEditing(true)}>
                            <Edit className="h-4 w-4 mr-2" /> Edit Plan
                        </Button>
                    </>
                )}

                {planId && (
                    <Sheet open={isHistoryOpen} onOpenChange={setIsHistoryOpen}>
                        <SheetTrigger asChild>
                            <Button variant="outline" size="sm">
                                <Clock className="h-4 w-4 mr-2" /> History
                            </Button>
                        </SheetTrigger>
                        <SheetContent>
                            <SheetHeader>
                                <SheetTitle>Version History</SheetTitle>
                            </SheetHeader>
                            <p className="text-sm text-muted-foreground mt-2 mb-4">
                                Click on a version to view it. Only the current version can be edited.
                            </p>
                            <div className="mt-4">
                                <PlanHistory
                                    planId={planId}
                                    selectedVersionId={selectedVersionId}
                                    onVersionSelect={(versionId, isCurrentVersion) => {
                                        handleVersionSelect(versionId, isCurrentVersion);
                                        // Close sheet after selection
                                        setIsHistoryOpen(false);
                                    }}
                                />
                            </div>
                        </SheetContent>
                    </Sheet>
                )}
            </div>
        </div>

        <TabsContent value="plan" className="space-y-4">
            {/* Plan View Toggle */}
            <div className="flex justify-end space-x-2 mb-2">
                <Button
                    variant={viewMode === 'therapist' ? 'default' : 'outline'}
                    onClick={() => setViewMode('therapist')}
                    size="sm"
                    className={cn(viewMode === 'therapist' && "pointer-events-none")}
                >
                    <Eye className="h-4 w-4 mr-2" /> Therapist View
                </Button>
                <Button
                    variant={viewMode === 'client' ? 'default' : 'outline'}
                    onClick={() => setViewMode('client')}
                    size="sm"
                    className={cn(viewMode === 'client' && "pointer-events-none")}
                >
                    <EyeOff className="h-4 w-4 mr-2" /> Client View
                </Button>
            </div>

            {viewMode === 'therapist' ? (
                <TherapistView plan={displayPlan} />
            ) : (
                <ClientView plan={displayPlan} />
            )}
        </TabsContent>

        <TabsContent value="goals">
            {planId && (
              <div className="rounded-md border p-4 bg-muted/10">
                <GoalTimeline planId={planId} />
              </div>
            )}
        </TabsContent>

        <TabsContent value="transcript">
            <div className="rounded-md border p-4 bg-muted/10">
                <div className="flex items-center gap-2 mb-4 text-muted-foreground">
                    <FileText className="h-4 w-4" />
                    <h3 className="font-medium">Session Transcript</h3>
                </div>
                <ScrollArea className="h-[60vh] w-full rounded-md border bg-background p-4">
                    <p className="whitespace-pre-wrap text-sm leading-relaxed font-mono">
                        {transcript || "No transcript available."}
                    </p>
                </ScrollArea>
            </div>
        </TabsContent>
      </Tabs>

      {/* AI Disclaimer Footer */}
      <div className="mt-8 p-4 text-sm text-center text-muted-foreground bg-accent/20 rounded-md border">
        {AI_DISCLAIMER}
      </div>

      {/* Suggestion Review Dialog */}
      <Dialog open={!!selectedSuggestion} onOpenChange={(open) => {
        if (!open && !isProcessing) {
          setSelectedSuggestion(null);
        }
      }}>
        <DialogContent className="max-w-4xl w-[calc(100vw-2rem)] max-h-[calc(100vh-2rem)] overflow-hidden p-6">
          <DialogHeader>
            <DialogTitle>Review AI Suggestions</DialogTitle>
            <DialogDescription>
              Review the suggested changes before applying them to the treatment plan
            </DialogDescription>
          </DialogHeader>
          {selectedSuggestion && (
            <SuggestionReviewPanel
              suggestionId={selectedSuggestion.id}
              sessionSummary={selectedSuggestion.sessionSummary}
              progressNotes={selectedSuggestion.progressNotes}
              suggestedChanges={selectedSuggestion.suggestedChanges}
              currentPlan={plan}
              createdAt={selectedSuggestion.createdAt}
              onApprove={handleApprove}
              onReject={handleReject}
              isLoading={isProcessing}
            />
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}