'use client'

import { useState } from 'react';
import { TreatmentPlan } from '@/lib/schemas/plan';
import { TherapistView } from './TherapistView';
import { ClientView } from './ClientView';
import { PlanEditor } from './PlanEditor';
import { PlanHistory } from './PlanHistory';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertCircle, Eye, EyeOff, Edit, Clock, FileText } from 'lucide-react';
import { SafetyCheckResult, RiskLevel } from '@/lib/types/safety';
import { cn } from '@/lib/utils';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from '@/components/ui/scroll-area';

interface DualViewPlanProps {
  plan: TreatmentPlan;
  planId?: string; // Needed for API updates
  safetyResult?: SafetyCheckResult;
  transcript?: string;
  onPlanUpdated?: (newPlan: TreatmentPlan) => void; // Callback to parent to refresh
}

type ViewMode = 'therapist' | 'client';

const AI_DISCLAIMER = "Generated by AI Assistant. This is not a substitute for clinical judgment. Please review carefully.";

export function DualViewPlan({ plan: initialPlan, planId, safetyResult, transcript, onPlanUpdated }: DualViewPlanProps) {
  const [plan, setPlan] = useState<TreatmentPlan>(initialPlan);
  const [viewMode, setViewMode] = useState<ViewMode>('therapist');
  const [isEditing, setIsEditing] = useState(false);

  const isHighRisk = safetyResult && safetyResult.riskLevel === RiskLevel.HIGH;

  const handleSave = async (updatedPlan: TreatmentPlan) => {
    if (!planId) {
        // If no ID (e.g. demo mock mode), just update local state
        setPlan(updatedPlan);
        setIsEditing(false);
        return;
    }

    // Call API
    const res = await fetch(`/api/plans/${planId}/update`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updatedPlan)
    });

    if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || "Failed to update plan");
    }

    // Success
    setPlan(updatedPlan);
    setIsEditing(false);
    if (onPlanUpdated) onPlanUpdated(updatedPlan);
  };

  if (isEditing) {
      return <PlanEditor plan={plan} onSave={handleSave} onCancel={() => setIsEditing(false)} />;
  }

  return (
    <div className="space-y-6">
      {/* Safety Alert Banner */}
      {isHighRisk && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Safety Alert Detected</AlertTitle>
          <AlertDescription>
            {safetyResult.reasoning || "High-risk content was identified during analysis. Please review this plan with extreme caution."}
          </AlertDescription>
        </Alert>
      )}

      <Tabs defaultValue="plan" className="w-full">
        <div className="flex justify-between items-center mb-4">
            <TabsList>
                <TabsTrigger value="plan">Treatment Plan</TabsTrigger>
                <TabsTrigger value="transcript" disabled={!transcript}>
                    Transcript
                </TabsTrigger>
            </TabsList>

            <div className="flex gap-2 items-center">
                <Button variant="outline" size="sm" onClick={() => setIsEditing(true)}>
                    <Edit className="h-4 w-4 mr-2" /> Edit Plan
                </Button>
                
                {planId && (
                    <Sheet>
                        <SheetTrigger asChild>
                            <Button variant="outline" size="sm">
                                <Clock className="h-4 w-4 mr-2" /> History
                            </Button>
                        </SheetTrigger>
                        <SheetContent>
                            <SheetHeader>
                                <SheetTitle>Version History</SheetTitle>
                            </SheetHeader>
                            <div className="mt-4">
                                <PlanHistory planId={planId} />
                            </div>
                        </SheetContent>
                    </Sheet>
                )}
            </div>
        </div>

        <TabsContent value="plan" className="space-y-4">
            {/* Plan View Toggle */}
            <div className="flex justify-end space-x-2 mb-2">
                <Button
                    variant={viewMode === 'therapist' ? 'default' : 'outline'}
                    onClick={() => setViewMode('therapist')}
                    size="sm"
                    className={cn(viewMode === 'therapist' && "pointer-events-none")}
                >
                    <Eye className="h-4 w-4 mr-2" /> Therapist View
                </Button>
                <Button
                    variant={viewMode === 'client' ? 'default' : 'outline'}
                    onClick={() => setViewMode('client')}
                    size="sm"
                    className={cn(viewMode === 'client' && "pointer-events-none")}
                >
                    <EyeOff className="h-4 w-4 mr-2" /> Client View
                </Button>
            </div>

            {viewMode === 'therapist' ? (
                <TherapistView plan={plan} />
            ) : (
                <ClientView plan={plan} />
            )}
        </TabsContent>

        <TabsContent value="transcript">
            <div className="rounded-md border p-4 bg-muted/10">
                <div className="flex items-center gap-2 mb-4 text-muted-foreground">
                    <FileText className="h-4 w-4" />
                    <h3 className="font-medium">Session Transcript</h3>
                </div>
                <ScrollArea className="h-[60vh] w-full rounded-md border bg-background p-4">
                    <p className="whitespace-pre-wrap text-sm leading-relaxed font-mono">
                        {transcript || "No transcript available."}
                    </p>
                </ScrollArea>
            </div>
        </TabsContent>
      </Tabs>

      {/* AI Disclaimer Footer */}
      <div className="mt-8 p-4 text-sm text-center text-muted-foreground bg-accent/20 rounded-md border">
        {AI_DISCLAIMER}
      </div>
    </div>
  );
}